package clientconfig

// The texts shared verbatim by both renderers live here as constants so the
// two outputs can never drift apart.

// NATNote matches the authhound-probe WS-3 registration-hint wording
// (internal/check/reachability.go in that repo) — keep the two in sync.
const NATNote = `Note: if NAT sits between the client and the server, the server sees a
different source IP — register the post-NAT address instead.`

// CoANote is appended to both outputs when Request.CoANote is set. CoA is
// out of scope for a client registration; the note exists so nobody expects
// this block to have configured it.
const CoANote = `Note: CoA/Disconnect (RFC 5176) is received by the NAS on a separate
port, typically UDP 3799 — registering this client does not configure CoA.`

// entropyNote describes a generated secret; args: length, charset size, bits.
const entropyNote = "Secret: %d chars from a %d-symbol set ≈ %d bits of entropy."

// generatedBy heads both outputs; the trust statement is the product.
const generatedBy = "generated by radius-client-config (runs locally; nothing is transmitted)"
